# iam-apiserver配置文件

# RESTful服务配置
server:
  mode: debug # server mode: release, debug, test. 默认为release
  healthz: true # 是否开启健康检查，如果开启会安装/healthz路由，默认为true
  middlewares: recovery,logger,secure,nocache,cors,dump # 加载的 gin 中间件列表，多个中间件，逗号(,)隔开
  max-ping-count: 3 # http 服务启动后，自检尝试次数，默认 3

# GRPC服务配置
grpc:
  bind-address: ${IAM_APISERVER_GRPC_BIND_ADDRESS} # grpc 安全模式的 IP 地址，默认 0.0.0.0
  bind-port: ${IAM_APISERVER_GRPC_BIND_PORT} # grpc 安全模式的端口号，默认 8081

# HTTP配置
insecure:
  bind-address:  ${IAM_APISERVER_INSECURE_BIND_ADDRESS} # 绑定的不安全 IP 地址，设置为 0.0.0.0 表示使用全部网络接口，默认为 127.0.0.1
  bind-port:  ${IAM_APISERVER_INSECURE_BIND_PORT} # 提供非安全认证的监听端口，默认为 8080

# HTTPS配置
secure:
  bind-address:  ${IAM_APISERVER_SECURE_BIND_ADDRESS} # HTTPS 安全模式的 IP 地址，默认为 0.0.0.0
  bind-port: ${IAM_APISERVER_SECURE_BIND_PORT}  # 使用 HTTPS 安全模式的端口号，设置为 0 表示不启用 HTTPS，默认为 8443
  tls:
    #cert-dir: .iam/cert # TLS 证书所在的目录，默认值为 /var/run/iam
    #pair-name: iam # TLS 私钥对名称，默认 iam
      cert-key:
        cert-file: ${IAM_APISERVER_SECURE_TLS_CERT_KEY_CERT_FILE} # 包含 x509 证书的文件路径，用 HTTPS 认证
        private-key-file: ${IAM_APISERVER_SECURE_TLS_CERT_KEY_PRIVATE_KEY_FILE} # TLS 私钥

# MySQL数据库相关配置
mysql:
  